name: Deploy

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Copy to zacharygranger.ca S3
        run: aws s3 sync ./. s3://zacharygranger.ca
              --exclude '.github/*'
              --exclude '.git/*'
              --exclude '.gitignore'
              --exclude 'VSCode Projects.code-workspace'
              --delete
      - name: Copy to www.zacharygranger.ca S3
        run: aws s3 sync ./. s3://www.zacharygranger.ca
              --exclude '.github/*'
              --exclude '.git/*'
              --exclude '.gitignore'
              --exclude 'VSCode Projects.code-workspace'
              --delete
      - name: Invalidate cache for zacharygranger.ca Cloudfront distibution
        run: aws cloudfront create-invalidation --distribution-id E2A8KUQXU9I05H --paths '/*'
      - name: Invalidate cache for www.zacharygranger.ca Cloudfront distibution
        run: aws cloudfront create-invalidation --distribution-id E3DV9S4HY2FFDJ --paths '/*'